USE `condologix`;

ALTER TABLE TERMINAL
ADD CONSTRAINT FK_ID_CONDOMINIUM_TERMINAL
FOREIGN KEY (ID_CONDOMINIUM) REFERENCES CONDOMINIUM (ID_CONDOMINIUM);

ALTER TABLE RESIDENT
ADD CONSTRAINT FK_ID_TERMINAL_RESIDENT
FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINAL (ID_TERMINAL);

ALTER TABLE CONCIERGE
ADD CONSTRAINT FK_ID_CONDOMINIUM_CONCIERGE
FOREIGN KEY (ID_CONDOMINIUM) REFERENCES CONDOMINIUM (ID_CONDOMINIUM);

ALTER TABLE PACKAGE
ADD CONSTRAINT FK_USER_NAME_EMAIL_PACKAGE
FOREIGN KEY (USER_NAME_EMAIL) REFERENCES RESIDENT (USER_NAME_EMAIL),
ADD CONSTRAINT FK_ID_TERMINAL_PACKAGE
FOREIGN KEY (ID_TERMINAL) REFERENCES TERMINAL (ID_TERMINAL),
ADD CONSTRAINT FK_ID_RESIDENT_PACKAGE
FOREIGN KEY (ID_RESIDENT) REFERENCES RESIDENT (ID_RESIDENT),
ADD CONSTRAINT FK_ID_CONCIERGE_PACKAGE
FOREIGN KEY (ID_CONCIERGE) REFERENCES CONCIERGE (ID_CONCIERGE);

ALTER TABLE NOTIFICATION
ADD CONSTRAINT FK_ID_PACKAGE_NOTIFICATION
FOREIGN KEY (ID_PACKAGE) REFERENCES PACKAGE (ID_PACKAGE);
